### ISSUE TITLE
Forks Problem

### ISSUE THREAD

**Issue by ghost** [MohamedDahman/Kitchen#1]
Hey Mohammad, 
be careful of how many persons forked your repository, i think Hosam didn't forked it and he is working on your master branch, in other words, your code could destroy if he does *git push*

you can check from here : https://github.com/MohamedDahman/Kitchen/network/members

**Comment by MohamedDahman** [comment]
thank you very much dear  Wael , i check it every one make fork except Ismeal did not make fork
